### ISSUE TITLE
Nodes is being continuously recreated.

### ISSUE THREAD

**Issue by paradoxe35** [jedrw/kproximate#20]
Hey @jedrw,

Thanks for this beautiful project. However, while conducting my tests, I've noticed that the nodes are being recreated continuously, scaling up and down repeatedly.

I have a cluster based on K0S with three workers and one controller. After applying the deployment file below, I have six replicas, with two pending due to `Insufficient memory`. This triggers the scaler, causing it to scale up and down repeatedly.

Could you please help identify the issue? I would like to use this, in my small Proxmox setup.

Here is my Deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 8
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          resources:
            limits:
              cpu: "1"
              memory: "2048Mi"
            requests:
              cpu: "1"
              memory: "1024Mi"
          image: nginx:1.14.2
          ports:
            - containerPort: 80
```
